### PR TITLE
Split long list into separate lists combined

### PR DESCRIPTION
**Pull request by stephenreddek**
To address https://github.com/elm-lang/elm-compiler/issues/1521

### CODE REVIEW

**Comment by stephenreddek** [comment]
The large diff is due to the way elm-format decided to format it. The long list is split into 3 sub-lists.

**Comment by teepark** [comment]
Great, thanks @stephenreddek!

**Comment by stephenreddek** [comment]
Thank you for merging it! Will you able to bump the version and push it up to the package repo? I'd like to use this in a project.

**Comment by teepark** [comment]
Done. Thanks for the reminder :)

**Pull request merged**
